# RAID monitoring for Broadcom/LSI MegaRAID

# Main metrics
UserParameter=raid.cvbbu.status[*],/usr/local/lib/zabbix/scripts/raid_cv-bbu_status.sh $1
UserParameter=raid.pdisk.status[*],/usr/local/lib/zabbix/scripts/raid_pdisk_status.sh $1

# Virtual disk counters


# Physical disk counters
UserParameter=raid.pdisk.total.count[*],/usr/local/lib/zabbix/scripts/raid_pdisk_status.sh $1 | /usr/bin/jq 'length'
UserParameter=raid.pdisk.online.count[*],/usr/local/lib/zabbix/scripts/raid_pdisk_status.sh $1 | /usr/bin/jq '[.[] | select(.state == "Onln")] | length'
UserParameter=raid.pdisk.failed.count[*],/usr/local/lib/zabbix/scripts/raid_pdisk_status.sh $1 | /usr/bin/jq '[.[] | select(.state | IN("Failed", "Offline"))] | length'
UserParameter=raid.pdisk.hotspare.count[*],/usr/local/lib/zabbix/scripts/raid_pdisk_status.sh $1 | /usr/bin/jq '[.[] | select(.state == "DHS")] | length'

# Disk health metrics


# CacheVault/BBU status
UserParameter=raid.cvbbu.status.text[*],/usr/local/lib/zabbix/scripts/raid_cv-bbu_status.sh $1 | /usr/bin/jq -r '.status'
UserParameter=raid.cvbbu.temperature[*],/usr/local/lib/zabbix/scripts/raid_cv-bbu_status.sh $1 | /usr/bin/jq '.temperature // 0'
