# RAID monitoring for Broadcom/LSI MegaRAID

# Main metrics
UserParameter=raid.cvbbu.status[*],/usr/local/lib/zabbix/scripts/raid_cv-bbu_status.sh $1

# Virtual disk counters


# Physical disk counters


# Disk health metrics


# CacheVault/BBU status
UserParameter=raid.cvbbu.status.text[*],/usr/local/lib/zabbix/scripts/raid_cv-bbu_status.sh $1 | /usr/bin/jq -r '.status'
UserParameter=raid.cvbbu.temperature[*],/usr/local/lib/zabbix/scripts/raid_cv-bbu_status.sh $1 | /usr/bin/jq '.temperature // 0'
